apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      serviceAccount: nfd-worker
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nfd-worker
          image: gcr.lank8s.cn/k8s-staging-nfd/node-feature-discovery:master
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-worker"
          args:
            - "-server=nfd-master:8080"
            - --label-conf-dir=/etc/kubernetes/node-feature-discovery/
          volumeMounts:
            - mountPath: /etc/kubernetes/node-feature-discovery
              name: label-conf
      volumes:
        - name: label-conf
          configMap:
            name: nfd-labels-config
            items:
              - key: labels.yaml
                path: labels.yaml