kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-csi-pvc
spec:
  storageClassName: openebs-jiva-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi