apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  serviceName: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: hello-container
          image: busybox
          command:
            - sh
            - -c
            - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
          volumeMounts:
            - mountPath: /mnt/store
              name: cstor-pvc1
  volumeClaimTemplates:
    - metadata:
        name: cstor-pvc1
      spec:
        storageClassName: cstor-csi-disk
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
